In [ ]:
# Numpy:(numarical python)
#is is a open souce library for numarical and scientific computing.


import numpy as np

li=[12,34,78,23]

a=np.array(li)

b=np.array({'a':1,'b':2})
b


array({'a': 1, 'b': 2}, dtype=object)

In [ ]:
# ndim: to find the diamension of an array
a.ndim
c=np.array([[12,13,14],[22,23,24]])
c.ndim

2

In [ ]:
#dtype: to find the datatype of array.

b.dtype

d=np.array('python')
d.dtype
a.dtype

dtype('int64')

In [ ]:
# shape: it will returns the shape of array(rows*col*values)

a
a.shape
c
c.shape

(2, 3)

In [ ]:
# size: number of elements

a.size
c.size

6

In [ ]:
# itemsize:

a.itemsize

w=np.array('python')
w.itemsize

24

In [ ]:
a.nbytes
w.nbytes

24

In [ ]:
# arange: used to generate sequence of values.
# np.arange(start,end,step,dtype=None)

ab=np.arange(1,11,2,dtype=None)
ab

array([1, 3, 5, 7, 9])

In [ ]:
# reshape:it rearranges the elements into a new shape.

x=np.arange(12)
#x.reshape(1,11)
x.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
# linspace(): to generate evenly spaced numbers between two given values
# np.linspace(start,end,num=10,endpoint=True,retstep=False,dtype=Float)
a=np.linspace(0,10,num=20,endpoint=True,retstep=False,dtype=bool)
a

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [ ]:
# zeros(): it will create an array filled with zero.
# np.zeros(shape,dtype=Float)
b=np.zeros((2,3),dtype=int)
b

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
#ones()
c=np.ones((2,4),dtype=int)
c

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
#indentity: np.identity(shape,dtype=float)

d=np.identity(4,dtype=bool)
d

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [ ]:
# randint: to generate random integer values.

# syntex: np.random.randint(low,high=None,size=None,dtype=int)


e=np.random.randint(1,10,size=6)
e

array([2, 5, 5, 6, 4, 2])

In [ ]:
# rand():
f=np.random.rand(5)*5
f

array([4.00541674, 2.47291042, 3.62121496, 3.05558822, 4.68287577])

In [ ]:
# Indexing:=>

a=np.array([23,44,56,12])
a[-1]

# var_name[row,col]
b=np.array([[12,34,56],[11,23,78]])
b[1,1]
b[0,2]

np.int64(56)

In [ ]:
# boolean filtering:

a=np.arange(1,51)
a
#var_name[condition]
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [ ]:
#slicing:

b=np.array([12,45,65,34,89,44])
b[1::2]


c=np.array([[13,16,19],[12,14,16]])
c[1][0:2:1]

#var[row_slicing,col_slicing]
c[1,0:2]


array([12, 14])

In [ ]:
x=np.array([11,22,33])
y=np.array([10,20,30])
x+y
x-y
x*y
x/y

x==y
x>y

x^y

array([ 1,  2, 63])

In [ ]:
#all(): to check all values are zero or not.
x.all()


np.True_

In [ ]:
x.sum()
x.min()
x.max()
np.size(x)
np.sort(x)
np.mean(x)
np.median(x)

np.float64(22.0)